name: Download ZIP from Azure Storage and Commit to Repo

on:
  workflow_dispatch:

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Create folder for artifact
        run: mkdir -p artifacts

      - name: Download ZIP from Azure Storage
        run: |
          curl -L "${{ secrets.AZURE_SAS_URL }}" -o artifacts/portal-20250514-362.zip

      - name: Configure Git
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

      - name: Commit and Push ZIP file using PAT
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add artifacts/portal-20250514-362.zip
          git diff --cached --quiet || git commit -m "Add ZIP artifact from Azure Storage"

          # Force replace the remote to use your PAT
          git remote remove origin
          git remote add origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}

          # Push to the correct branch
          git push origin HEAD:main
