name: Upload Artifact ZIP to Repo

on:
  workflow_dispatch:

jobs:
  push-zip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Download ZIP from Azure Blob
        run: |
          mkdir -p artifacts
          curl -L "https://vadevbuildartifactstore.blob.core.windows.net/buildartifactzip/portal-20250514-362.zip?sv=2024-11-04&ss=bfqt&srt=sco&sp=rwdlacupiytfx&se=2025-06-12T12:52:39Z&st=2025-06-10T04:52:39Z&spr=https&sig=EAtc55%2B7GlQnDeYvxxHBl%2BzB8PaUZhY%2Fg7kN9TYSNzw%3D" -o artifacts/portal-20250514-362.zip

      - name: Commit and push ZIP file
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git add artifacts/portal-20250514-362.zip
          git diff --cached --quiet || git commit -m "Add ZIP artifact from Azure Storage"

          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/${{ github.repository }}
          git push origin HEAD:main
